### ISSUE TITLE
[수정요청] 게시판 쓰기 관련 수정 사항 및 검토 내용

### ISSUE THREAD

**Issue by Sophoca** [AjouCola/Cola_Web#62]
게시글 쓰기
- [x] 제목과 내용 사이 divider 삽입
- [x] 제목 미리보기 기본 사이즈 H1 적용
- [x] 빈 태그 입력 방지
- [x] 빈 태그를 포함하여 여러 태그를 추가하고, 이후 빈 태그를 삭제할 경우 제대로 동작하지 않는 문제

검토내용
- 태그 입력 시 표시되는 글자 수가 너무 적지 않은지
- 태그 창 크기 및 글자 크기를 줄이는게 어떨지
- 태그 입력 창 배경색이 없어서 잘 보이지 않는 부분 수정이 필요할지

**Comment by dmstmdrbs** [comment]
Toast UI 에디터로 전환하면서 수정 및 반영하도록 하겠습니다

**Comment by dmstmdrbs** [comment]
수정했습니다
