### ISSUE TITLE
[수정요청] 게시글 쓰기 수정사항2

### ISSUE THREAD

**Issue by Sophoca** [AjouCola/Cola_Web#64]
<img width="1253" alt="image" src="https://user-images.githubusercontent.com/11497528/170829938-c47025d8-51c6-4f20-8a4a-0c842ca59557.png">

- [x] 상단 컴포넌트 높이가 vh로 지정되어 있어 태그를 많이 입력할 경우 화면비를 따라 비율이 유지되지 않는 문제
- [x] 태그를 많이 입력하더라도 태그들을 담는 컴포넌트 내에서 스크롤 가능하도록 변경하는 것 제안
- [x] 같은 태그에 대한 중복 처리 필요
- [x] 프론트에서도 자체적으로 lowerCase를 적용하여 태그의 일관성 유지 제안
- [x] 마크다운 뷰어가 제대로 동작하지 않는 문제

**Comment by Coreight98** [comment]
해결하였습니다. 감사합니다.

**Comment by Sophoca** [comment]
@Coreight98 

- [ ] 태그를 여러 개 입력할 경우 칩 높이가 일정하게 유지되지 않는 문제

<div>
<img width="197" alt="스크린샷 2022-05-29 오후 7 02 59" src="https://user-images.githubusercontent.com/11497528/170862640-4ad6a420-4db8-4f92-8fb3-f01084d9364c.png">
<img width="202" alt="스크린샷 2022-05-29 오후 7 03 57" src="https://user-images.githubusercontent.com/11497528/170862641-40f95a0f-f40e-45ed-9e17-ca5bcaa9e7ad.png">
</div>

**Comment by dmstmdrbs** [comment]
@Sophoca '잘 동장하지 않는다' 라는게  정확히 무슨 의미였었죠??

**Comment by Sophoca** [comment]
@dmstmdrbs 마크다운 뷰어가 적용되지 않아, 글을 작성할 때는 preview 상으로 마크다운 스타일이 적용된 상태로 보이지만 글 작성을 완료한 이후 해당 글을 조회하면 스타일이 제대로 적용되지 않는 상황입니다.

**Comment by dmstmdrbs** [comment]
수정 완료했습니다.
