### ISSUE TITLE
[수정요청] 댓글 수정사항

### ISSUE THREAD

**Issue by Sophoca** [AjouCola/Cola_Web#65]
<img width="1194" alt="image" src="https://user-images.githubusercontent.com/11497528/170830825-5dd35c2d-3fbf-4ece-b56c-9d19ce1ea5e2.png">

- [x] qna 게시판이 아닌 일반 게시판에서 댓글 수정 시, 마크다운 에디터가 나오는 문제
- [x] qna 게시판이 아닌 일반 게시판 댓글에 마크다운 형식으로 작성 시, 마크다운 뷰어가 적용되어 나오는 상황 (논의 필요)

**Comment by Coreight98** [comment]
수정하였습니다 감사합니다!
